### ISSUE TITLE
Possible git checkout error

### ISSUE THREAD

**Issue by cg122** [fasten-project/quality-analyzer#18]
# Problem

A message should be processed and error is not so clear. See bellow a message from err topic. 

A guess is that git has problems checkout from repo. Permission issue?

```json
{
  "plugin_name": "RapidPlugin",
  "plugin_version": "0.0.1",
  "input": {
    "repoUrl": "https://github.com/openzipkin/zipkin-aws",
    "date": 1523246397,
    "repoType": "git",
    "forge": "mvn",
    "groupId": "io.zipkin.aws",
    "sourcesUrl": "",
    "artifactId": "zipkin-aws-parent",
    "repoPath": "/mnt/fasten/repos/i/io.zipkin.aws/zipkin-aws-parent",
    "version": "0.9.1",
    "commitTag": "0.9.1"
  },
  "created_at": "1604573589.523785",
  "error": "/mnt/fasten/repos/i/io.zipkin.aws/zipkin-aws-parent"
}
```

**Comment by MagielBruntink** [comment]
git user & email are set within the Dockerfile, so that should not be the issue.
The error message is not very helpful, let's try to find the assert that produced it.

**Comment by cg122** [comment]
Indeed, I realised this. I guess the error message comes from gitpython package. I added a new integration testing to justify it.

**Comment by cg122** [comment]
`gitpython` raise `NoSuchPathError`, the error string is the repo path. So I guess it is the problem to use absolute path of monster from the docker. I will figure out if it is the case.

**Comment by cg122** [comment]
This is k8s deployment issue, new [deployment file](https://github.com/fasten-project/k8s-deployments/commit/46b9e08d5cbaaa573015ed4f441db3c15ca47d03) solved the issue.
