### ISSUE TITLE
New version of `fasten` library

### ISSUE THREAD

**Issue by StefanosChaliasos** [fasten-project/quality-analyzer#20]
I saw that you specify `fasten` library in `setup.py` without a specific version tag. FYI, I updated the `fasten` library to implement `skip_messages` and `free_resource` methods in `KafkaPlugin`, and I also added `KafkaPluginNonBlocking`. Those changes shouldn't break your plug-in.

**Comment by MagielBruntink** [comment]
Thank you @StefanosChaliasos
I updated our plugin to use the KafkaPluginNonBlocking from the fasten python library.
Fixed in [0cb5d2b](https://github.com/fasten-project/quality-analyzer/commit/0cb5d2bd62055166eab662560df8dd9cf1baca9b).
